card_mapping = {
    '3': [{'name': 'SOLO', 'main': '3', 'type': 1, 'rl': 0}],
    '4': [{'name': 'SOLO', 'main': '4', 'type': 1, 'rl': 1}],
    '5': [{'name': 'SOLO', 'main': '5', 'type': 1, 'rl': 2}],
    '6': [{'name': 'SOLO', 'main': '6', 'type': 1, 'rl': 3}],
    '7': [{'name': 'SOLO', 'main': '7', 'type': 1, 'rl': 4}],
    '8': [{'name': 'SOLO', 'main': '8', 'type': 1, 'rl': 5}],
    '9': [{'name': 'SOLO', 'main': '9', 'type': 1, 'rl': 6}],
    'T': [{'name': 'SOLO', 'main': 'T', 'type': 1, 'rl': 7}],
    'J': [{'name': 'SOLO', 'main': 'J', 'type': 1, 'rl': 8}],
    'Q': [{'name': 'SOLO', 'main': 'Q', 'type': 1, 'rl': 9}],
    'K': [{'name': 'SOLO', 'main': 'K', 'type': 1, 'rl': 10}],
    'A': [{'name': 'SOLO', 'main': 'A', 'type': 1, 'rl': 11}],
    '2': [{'name': 'SOLO', 'main': '2', 'type': 1, 'rl': 12}],
    'B': [{'name': 'SOLO', 'main': 'B', 'type': 1, 'rl': 13}],
    'R': [{'name': 'SOLO', 'main': 'R', 'type': 1, 'rl': 14}],

    '33': [{'name': 'PAIR', 'main': '3', 'type': 2, 'rl': 15}],
    '44': [{'name': 'PAIR', 'main': '4', 'type': 2, 'rl': 16}],
    '55': [{'name': 'PAIR', 'main': '5', 'type': 2, 'rl': 17}],
    '66': [{'name': 'PAIR', 'main': '6', 'type': 2, 'rl': 18}],
    '77': [{'name': 'PAIR', 'main': '7', 'type': 2, 'rl': 19}],
    '88': [{'name': 'PAIR', 'main': '8', 'type': 2, 'rl': 20}],
    '99': [{'name': 'PAIR', 'main': '9', 'type': 2, 'rl': 21}],
    'TT': [{'name': 'PAIR', 'main': 'T', 'type': 2, 'rl': 22}],
    'JJ': [{'name': 'PAIR', 'main': 'J', 'type': 2, 'rl': 23}],
    'QQ': [{'name': 'PAIR', 'main': 'Q', 'type': 2, 'rl': 24}],
    'KK': [{'name': 'PAIR', 'main': 'K', 'type': 2, 'rl': 25}],
    'AA': [{'name': 'PAIR', 'main': 'A', 'type': 2, 'rl': 26}],
    '22': [{'name': 'PAIR', 'main': '2', 'type': 2, 'rl': 27}],

    '333': [{'name': 'TRIO', 'main': '3', 'type': 3, 'rl': 28}],
    '444': [{'name': 'TRIO', 'main': '3', 'type': 3, 'rl': 29}],
    '555': [{'name': 'TRIO', 'main': '5', 'type': 3, 'rl': 30}],
    '666': [{'name': 'TRIO', 'main': '6', 'type': 3, 'rl': 31}],
    '777': [{'name': 'TRIO', 'main': '7', 'type': 3, 'rl': 32}],
    '888': [{'name': 'TRIO', 'main': '8', 'type': 3, 'rl': 33}],
    '999': [{'name': 'TRIO', 'main': '9', 'type': 3, 'rl': 34}],
    'TTT': [{'name': 'TRIO', 'main': 'T', 'type': 3, 'rl': 35}],
    'JJJ': [{'name': 'TRIO', 'main': 'J', 'type': 3, 'rl': 36}],
    'QQQ': [{'name': 'TRIO', 'main': 'Q', 'type': 3, 'rl': 37}],
    'KKK': [{'name': 'TRIO', 'main': 'K', 'type': 3, 'rl': 38}],
    'AAA': [{'name': 'TRIO', 'main': 'A', 'type': 3, 'rl': 39}],
    '222': [{'name': 'TRIO', 'main': '2', 'type': 3, 'rl': 40}],
    # 333*
    '3334': [{'sub': '4', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '3335': [{'sub': '5', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '3336': [{'sub': '6', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '3337': [{'sub': '7', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '3338': [{'sub': '8', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '3339': [{'sub': '9', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333T': [{'sub': 'T', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333J': [{'sub': 'J', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333Q': [{'sub': 'Q', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333K': [{'sub': 'K', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333A': [{'sub': 'A', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '3332': [{'sub': '2', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333B': [{'sub': 'B', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    '333R': [{'sub': 'R', 'main': '3', 'name': 'TRIO_ONE', 'type': 4, 'rl': 41}],
    # 444*
    '3444': [{'sub': '3', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '4445': [{'sub': '5', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '4446': [{'sub': '6', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '4447': [{'sub': '7', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '4448': [{'sub': '8', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '4449': [{'sub': '9', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444T': [{'sub': 'T', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444J': [{'sub': 'J', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444Q': [{'sub': 'Q', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444K': [{'sub': 'K', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444A': [{'sub': 'A', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '4442': [{'sub': '2', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444B': [{'sub': 'B', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    '444R': [{'sub': 'R', 'main': '4', 'name': 'TRIO_ONE', 'type': 4, 'rl': 42}],
    # 555*
    '3555': [{'sub': '3', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '4555': [{'sub': '4', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '5556': [{'sub': '6', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '5557': [{'sub': '7', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '5558': [{'sub': '8', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '5559': [{'sub': '9', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555T': [{'sub': 'T', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555J': [{'sub': 'J', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555Q': [{'sub': 'Q', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555K': [{'sub': 'K', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555A': [{'sub': 'A', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '5552': [{'sub': '2', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555B': [{'sub': 'B', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    '555R': [{'sub': 'R', 'main': '5', 'name': 'TRIO_ONE', 'type': 4, 'rl': 43}],
    # 666*
    '3666': [{'sub': '3', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '4666': [{'sub': '4', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '5666': [{'sub': '5', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '6667': [{'sub': '7', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '6668': [{'sub': '8', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '6669': [{'sub': '9', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666T': [{'sub': 'T', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666J': [{'sub': 'J', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666Q': [{'sub': 'Q', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666K': [{'sub': 'K', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666A': [{'sub': 'A', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '6662': [{'sub': '2', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666B': [{'sub': 'B', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    '666R': [{'sub': 'R', 'main': '6', 'name': 'TRIO_ONE', 'type': 4, 'rl': 44}],
    # 777*
    '3777': [{'sub': '3', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '4777': [{'sub': '4', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '5777': [{'sub': '5', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '6777': [{'sub': '6', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '7778': [{'sub': '8', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '7779': [{'sub': '9', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777T': [{'sub': 'T', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777J': [{'sub': 'J', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777Q': [{'sub': 'Q', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777K': [{'sub': 'K', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777A': [{'sub': 'A', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '7772': [{'sub': '2', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777B': [{'sub': 'B', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    '777R': [{'sub': 'R', 'main': '7', 'name': 'TRIO_ONE', 'type': 4, 'rl': 45}],
    # 888*
    '3888': [{'sub': '3', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '4888': [{'sub': '4', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '5888': [{'sub': '5', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '6888': [{'sub': '6', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '7888': [{'sub': '7', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '8889': [{'sub': '9', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888T': [{'sub': 'T', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888J': [{'sub': 'J', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888Q': [{'sub': 'Q', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888K': [{'sub': 'K', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888A': [{'sub': 'A', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '8882': [{'sub': '2', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888B': [{'sub': 'B', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    '888R': [{'sub': 'R', 'main': '8', 'name': 'TRIO_ONE', 'type': 4, 'rl': 46}],
    # 999*
    '3999': [{'sub': '3', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '4999': [{'sub': '4', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '5999': [{'sub': '5', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '6999': [{'sub': '6', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '7999': [{'sub': '7', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '8999': [{'sub': '8', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999T': [{'sub': 'T', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999J': [{'sub': 'J', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999Q': [{'sub': 'Q', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999K': [{'sub': 'K', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999A': [{'sub': 'A', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '9992': [{'sub': '2', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999B': [{'sub': 'B', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    '999R': [{'sub': 'R', 'main': '9', 'name': 'TRIO_ONE', 'type': 4, 'rl': 47}],
    # TTT*
    '3TTT': [{'sub': '3', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    '4TTT': [{'sub': '4', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    '5TTT': [{'sub': '5', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    '6TTT': [{'sub': '6', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    '7TTT': [{'sub': '7', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    '8TTT': [{'sub': '8', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    '9TTT': [{'sub': '9', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTTJ': [{'sub': 'J', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTTQ': [{'sub': 'Q', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTTK': [{'sub': 'K', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTTA': [{'sub': 'A', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTT2': [{'sub': '2', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTTB': [{'sub': 'B', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    'TTTR': [{'sub': 'R', 'main': 'T', 'name': 'TRIO_ONE', 'type': 4, 'rl': 48}],
    # JJJ*
    '3JJJ': [{'sub': '3', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    '4JJJ': [{'sub': '4', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    '5JJJ': [{'sub': '5', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    '6JJJ': [{'sub': '6', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    '7JJJ': [{'sub': '7', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    '8JJJ': [{'sub': '8', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    '9JJJ': [{'sub': '9', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'TJJJ': [{'sub': 'T', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'JJJQ': [{'sub': 'Q', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'JJJK': [{'sub': 'K', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'JJJA': [{'sub': 'A', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'JJJ2': [{'sub': '2', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'JJJB': [{'sub': 'B', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    'JJJR': [{'sub': 'R', 'main': 'J', 'name': 'TRIO_ONE', 'type': 4, 'rl': 49}],
    # QQQ*
    '3QQQ': [{'sub': '3', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    '4QQQ': [{'sub': '4', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    '5QQQ': [{'sub': '5', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    '6QQQ': [{'sub': '6', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    '7QQQ': [{'sub': '7', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    '8QQQ': [{'sub': '8', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    '9QQQ': [{'sub': '9', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'TQQQ': [{'sub': 'T', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'JQQQ': [{'sub': 'J', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'QQQK': [{'sub': 'K', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'QQQA': [{'sub': 'A', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'QQQ2': [{'sub': '2', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'QQQB': [{'sub': 'B', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    'QQQR': [{'sub': 'R', 'main': 'Q', 'name': 'TRIO_ONE', 'type': 4, 'rl': 50}],
    # KKK*
    '3KKK': [{'sub': '3', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    '4KKK': [{'sub': '4', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    '5KKK': [{'sub': '5', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    '6KKK': [{'sub': '6', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    '7KKK': [{'sub': '7', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    '8KKK': [{'sub': '8', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    '9KKK': [{'sub': '9', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'TKKK': [{'sub': 'T', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'JKKK': [{'sub': 'J', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'QKKK': [{'sub': 'Q', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'KKKA': [{'sub': 'A', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'KKK2': [{'sub': '2', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'KKKB': [{'sub': 'B', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    'KKKR': [{'sub': 'R', 'main': 'K', 'name': 'TRIO_ONE', 'type': 4, 'rl': 51}],
    # AAA*
    '3AAA': [{'sub': '3', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    '4AAA': [{'sub': '4', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    '5AAA': [{'sub': '5', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    '6AAA': [{'sub': '6', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    '7AAA': [{'sub': '7', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    '8AAA': [{'sub': '8', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    '9AAA': [{'sub': '9', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'TAAA': [{'sub': 'T', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'JAAA': [{'sub': 'J', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'QAAA': [{'sub': 'Q', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'KAAA': [{'sub': 'K', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'AAA2': [{'sub': '2', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'AAAB': [{'sub': 'B', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    'AAAR': [{'sub': 'R', 'main': 'A', 'name': 'TRIO_ONE', 'type': 4, 'rl': 52}],
    # 222*
    '3222': [{'sub': '3', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '4222': [{'sub': '4', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '5222': [{'sub': '5', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '6222': [{'sub': '6', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '7222': [{'sub': '7', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '8222': [{'sub': '8', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '9222': [{'sub': '9', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    'T222': [{'sub': 'T', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    'J222': [{'sub': 'J', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    'Q222': [{'sub': 'Q', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    'K222': [{'sub': 'K', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    'A222': [{'sub': 'A', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '222B': [{'sub': 'B', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    '222R': [{'sub': 'R', 'main': '2', 'name': 'TRIO_ONE', 'type': 4, 'rl': 53}],
    # 333**
    '33344': [{'sub': '4', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '33355': [{'sub': '5', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '33366': [{'sub': '6', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '33377': [{'sub': '7', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '33388': [{'sub': '8', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '33399': [{'sub': '9', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '333TT': [{'sub': 'T', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '333JJ': [{'sub': 'J', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '333QQ': [{'sub': 'Q', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '333KK': [{'sub': 'K', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '333AA': [{'sub': 'A', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    '33322': [{'sub': '2', 'main': '3', 'name': 'TRIO_TWO', 'type': 5, 'rl': 54}],
    # 444**
    '33444': [{'sub': '3', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '44455': [{'sub': '5', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '44466': [{'sub': '6', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '44477': [{'sub': '7', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '44488': [{'sub': '8', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '44499': [{'sub': '9', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '444TT': [{'sub': 'T', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '444JJ': [{'sub': 'J', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '444QQ': [{'sub': 'Q', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '444KK': [{'sub': 'K', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '444AA': [{'sub': 'A', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    '44422': [{'sub': '2', 'main': '4', 'name': 'TRIO_TWO', 'type': 5, 'rl': 55}],
    # 555**
    '33555': [{'sub': '3', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '44555': [{'sub': '4', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '55566': [{'sub': '6', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '55577': [{'sub': '7', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '55588': [{'sub': '8', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '55599': [{'sub': '9', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '555TT': [{'sub': 'T', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '555JJ': [{'sub': 'J', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '555QQ': [{'sub': 'Q', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '555KK': [{'sub': 'K', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '555AA': [{'sub': 'A', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    '55522': [{'sub': '2', 'main': '5', 'name': 'TRIO_TWO', 'type': 5, 'rl': 56}],
    # 666**
    '33666': [{'sub': '3', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '44666': [{'sub': '4', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '55666': [{'sub': '5', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '66677': [{'sub': '7', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '66688': [{'sub': '8', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '66699': [{'sub': '9', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '666TT': [{'sub': 'T', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '666JJ': [{'sub': 'J', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '666QQ': [{'sub': 'Q', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '666KK': [{'sub': 'K', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '666AA': [{'sub': 'A', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    '66622': [{'sub': '2', 'main': '6', 'name': 'TRIO_TWO', 'type': 5, 'rl': 57}],
    # 777**
    '33777': [{'sub': '3', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '44777': [{'sub': '4', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '55777': [{'sub': '5', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '66777': [{'sub': '6', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '77788': [{'sub': '8', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '77799': [{'sub': '9', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '777TT': [{'sub': 'T', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '777JJ': [{'sub': 'J', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '777QQ': [{'sub': 'Q', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '777KK': [{'sub': 'K', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '777AA': [{'sub': 'A', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    '77722': [{'sub': '2', 'main': '7', 'name': 'TRIO_TWO', 'type': 5, 'rl': 58}],
    # 888**
    '33888': [{'sub': '3', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '44888': [{'sub': '4', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '55888': [{'sub': '5', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '66888': [{'sub': '6', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '77888': [{'sub': '7', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '88899': [{'sub': '9', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '888TT': [{'sub': 'T', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '888JJ': [{'sub': 'J', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '888QQ': [{'sub': 'Q', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '888KK': [{'sub': 'K', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '888AA': [{'sub': 'A', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    '88822': [{'sub': '2', 'main': '8', 'name': 'TRIO_TWO', 'type': 5, 'rl': 59}],
    # 999**
    '33999': [{'sub': '3', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '44999': [{'sub': '4', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '55999': [{'sub': '5', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '66999': [{'sub': '6', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '77999': [{'sub': '7', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '88999': [{'sub': '8', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '999TT': [{'sub': 'T', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '999JJ': [{'sub': 'J', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '999QQ': [{'sub': 'Q', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '999KK': [{'sub': 'K', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '999AA': [{'sub': 'A', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    '99922': [{'sub': '2', 'main': '9', 'name': 'TRIO_TWO', 'type': 5, 'rl': 60}],
    # TTT**
    '33TTT': [{'sub': '3', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    '44TTT': [{'sub': '4', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    '55TTT': [{'sub': '5', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    '66TTT': [{'sub': '6', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    '77TTT': [{'sub': '7', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    '88TTT': [{'sub': '8', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    '99TTT': [{'sub': '9', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    'TTTJJ': [{'sub': 'J', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    'TTTQQ': [{'sub': 'Q', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    'TTTKK': [{'sub': 'K', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    'TTTAA': [{'sub': 'A', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    'TTT22': [{'sub': '2', 'main': 'T', 'name': 'TRIO_TWO', 'type': 5, 'rl': 61}],
    # JJJ**
    '33JJJ': [{'sub': '3', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    '44JJJ': [{'sub': '4', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    '55JJJ': [{'sub': '5', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    '66JJJ': [{'sub': '6', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    '77JJJ': [{'sub': '7', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    '88JJJ': [{'sub': '8', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    '99JJJ': [{'sub': '9', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    'TTJJJ': [{'sub': 'T', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    'JJJQQ': [{'sub': 'Q', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    'JJJKK': [{'sub': 'K', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    'JJJAA': [{'sub': 'A', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    'JJJ22': [{'sub': '2', 'main': 'J', 'name': 'TRIO_TWO', 'type': 5, 'rl': 62}],
    # QQQ**
    '33QQQ': [{'sub': '3', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    '44QQQ': [{'sub': '4', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    '55QQQ': [{'sub': '5', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    '66QQQ': [{'sub': '6', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    '77QQQ': [{'sub': '7', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    '88QQQ': [{'sub': '8', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    '99QQQ': [{'sub': '9', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    'TTQQQ': [{'sub': 'T', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    'JJQQQ': [{'sub': 'J', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    'QQQKK': [{'sub': 'K', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    'QQQAA': [{'sub': 'A', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    'QQQ22': [{'sub': '2', 'main': 'Q', 'name': 'TRIO_TWO', 'type': 5, 'rl': 63}],
    # KKK**
    '33KKK': [{'sub': '3', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    '44KKK': [{'sub': '4', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    '55KKK': [{'sub': '5', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    '66KKK': [{'sub': '6', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    '77KKK': [{'sub': '7', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    '88KKK': [{'sub': '8', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    '99KKK': [{'sub': '9', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    'TTKKK': [{'sub': 'T', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    'JJKKK': [{'sub': 'J', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    'QQKKK': [{'sub': 'Q', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    'KKKAA': [{'sub': 'A', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    'KKK22': [{'sub': '2', 'main': 'K', 'name': 'TRIO_TWO', 'type': 5, 'rl': 64}],
    # AAA**
    '33AAA': [{'sub': '3', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    '44AAA': [{'sub': '4', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    '55AAA': [{'sub': '5', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    '66AAA': [{'sub': '6', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    '77AAA': [{'sub': '7', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    '88AAA': [{'sub': '8', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    '99AAA': [{'sub': '9', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    'TTAAA': [{'sub': 'T', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    'JJAAA': [{'sub': 'J', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    'QQAAA': [{'sub': 'Q', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    'KKAAA': [{'sub': 'K', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    'AAA22': [{'sub': '2', 'main': 'A', 'name': 'TRIO_TWO', 'type': 5, 'rl': 65}],
    # 222**
    '33222': [{'sub': '3', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    '44222': [{'sub': '4', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    '55222': [{'sub': '5', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    '66222': [{'sub': '6', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    '77222': [{'sub': '7', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    '88222': [{'sub': '8', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    '99222': [{'sub': '9', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    'TT222': [{'sub': 'T', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    'JJ222': [{'sub': 'J', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    'QQ222': [{'sub': 'Q', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    'KK222': [{'sub': 'K', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],
    'AA222': [{'sub': 'A', 'main': '2', 'name': 'TRIO_TWO', 'type': 5, 'rl': 66}],

    # for sequence 'main' is the length of the sequence
    '34567': [{'sub': '3', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 67}],
    '45678': [{'sub': '4', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 68}],
    '56789': [{'sub': '5', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 69}],
    '6789T': [{'sub': '6', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 70}],
    '789TJ': [{'sub': '7', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 71}],
    '89TJQ': [{'sub': '8', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 72}],
    '9TJQK': [{'sub': '9', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 73}],
    'TJQKA': [{'sub': 'T', 'main': 5, 'type': 6, 'name': 'SEQUENCE', 'rl': 74}],

    '345678': [{'sub': '3', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 75}],
    '456789': [{'sub': '4', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 76}],
    '56789T': [{'sub': '5', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 77}],
    '6789TJ': [{'sub': '6', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 78}],
    '789TJQ': [{'sub': '7', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 79}],
    '89TJQK': [{'sub': '8', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 80}],
    '9TJQKA': [{'sub': '9', 'main': 6, 'type': 6, 'name': 'SEQUENCE', 'rl': 81}],

    '3456789': [{'sub': '3', 'main': 7, 'type': 6, 'name': 'SEQUENCE', 'rl': 82}],
    '456789T': [{'sub': '4', 'main': 7, 'type': 6, 'name': 'SEQUENCE', 'rl': 83}],
    '56789TJ': [{'sub': '5', 'main': 7, 'type': 6, 'name': 'SEQUENCE', 'rl': 84}],
    '6789TJQ': [{'sub': '6', 'main': 7, 'type': 6, 'name': 'SEQUENCE', 'rl': 85}],
    '789TJQK': [{'sub': '7', 'main': 7, 'type': 6, 'name': 'SEQUENCE', 'rl': 86}],
    '89TJQKA': [{'sub': '8', 'main': 7, 'type': 6, 'name': 'SEQUENCE', 'rl': 87}],

    '3456789T': [{'sub': '3', 'main': 8, 'type': 6, 'name': 'SEQUENCE', 'rl': 88}],
    '456789TJ': [{'sub': '4', 'main': 8, 'type': 6, 'name': 'SEQUENCE', 'rl': 89}],
    '56789TJQ': [{'sub': '5', 'main': 8, 'type': 6, 'name': 'SEQUENCE', 'rl': 90}],
    '6789TJQK': [{'sub': '6', 'main': 8, 'type': 6, 'name': 'SEQUENCE', 'rl': 91}],
    '789TJQKA': [{'sub': '7', 'main': 8, 'type': 6, 'name': 'SEQUENCE', 'rl': 92}],

    '3456789TJ': [{'sub': '3', 'main': 9, 'type': 6, 'name': 'SEQUENCE', 'rl': 93}],
    '456789TJQ': [{'sub': '4', 'main': 9, 'type': 6, 'name': 'SEQUENCE', 'rl': 94}],
    '56789TJQK': [{'sub': '5', 'main': 9, 'type': 6, 'name': 'SEQUENCE', 'rl': 95}],
    '6789TJQKA': [{'sub': '6', 'main': 9, 'type': 6, 'name': 'SEQUENCE', 'rl': 96}],

    '3456789TJQ': [{'sub': '3', 'main': 10, 'type': 6, 'name': 'SEQUENCE', 'rl': 97}],
    '456789TJQK': [{'sub': '4', 'main': 10, 'type': 6, 'name': 'SEQUENCE', 'rl': 98}],
    '56789TJQKA': [{'sub': '5', 'main': 10, 'type': 6, 'name': 'SEQUENCE', 'rl': 99}],

    '3456789TJQK': [{'sub': '3', 'main': 11, 'type': 6, 'name': 'SEQUENCE', 'rl': 100}],
    '456789TJQKA': [{'sub': '4', 'main': 11, 'type': 6, 'name': 'SEQUENCE', 'rl': 101}],

    '3456789TJQKA': [{'sub': '3', 'main': 12, 'type': 6, 'name': 'SEQUENCE', 'rl': 102}],

    '334455': [{'sub': '5', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 103}],
    '445566': [{'sub': '6', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 104}],
    '556677': [{'sub': '7', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 105}],
    '667788': [{'sub': '8', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 106}],
    '778899': [{'sub': '9', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 107}],
    '8899TT': [{'sub': 'T', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 108}],
    '99TTJJ': [{'sub': 'J', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 109}],
    'TTJJQQ': [{'sub': 'Q', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 110}],
    'JJQQKK': [{'sub': 'K', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 111}],
    'QQKKAA': [{'sub': 'A', 'main': 6, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 112}],

    '33445566': [{'sub': '6', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 113}],
    '44556677': [{'sub': '7', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 114}],
    '55667788': [{'sub': '8', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 115}],
    '66778899': [{'sub': '9', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 116}],
    '778899TT': [{'sub': 'T', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 117}],
    '8899TTJJ': [{'sub': 'J', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 118}],
    '99TTJJQQ': [{'sub': 'Q', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 119}],
    'TTJJQQKK': [{'sub': 'K', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 120}],
    'JJQQKKAA': [{'sub': 'A', 'main': 8, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 121}],

    '3344556677': [{'sub': '7', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 122}],
    '4455667788': [{'sub': '8', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 123}],
    '5566778899': [{'sub': '9', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 124}],
    '66778899TT': [{'sub': 'T', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 125}],
    '778899TTJJ': [{'sub': 'J', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 126}],
    '8899TTJJQQ': [{'sub': 'Q', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 127}],
    '99TTJJQQKK': [{'sub': 'K', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl:': 128}],
    'TTJJQQKKAA': [{'sub': 'A', 'main': 10, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl:': 129}],

    '334455667788': [{'sub': '8', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 130}],
    '445566778899': [{'sub': '9', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 131}],
    '5566778899TT': [{'sub': 'T', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 132}],
    '66778899TTJJ': [{'sub': 'J', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 133}],
    '778899TTJJQQ': [{'sub': 'Q', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 134}],
    '8899TTJJQQKK': [{'sub': 'K', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 135}],
    '99TTJJQQKKAA': [{'sub': 'A', 'main': 12, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 136}],

    '33445566778899': [{'sub': '9', 'main': 14, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 137}],
    '445566778899TT': [{'sub': 'T', 'main': 14, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 138}],
    '5566778899TTJJ': [{'sub': 'J', 'main': 14, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 139}],
    '66778899TTJJQQ': [{'sub': 'Q', 'main': 14, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 140}],
    '778899TTJJQQKK': [{'sub': 'K', 'main': 14, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 141}],
    '8899TTJJQQKKAA': [{'sub': 'A', 'main': 14, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 142}],

    '33445566778899TT': [{'sub': 'T', 'main': 16, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 143}],
    '445566778899TTJJ': [{'sub': 'J', 'main': 16, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 144}],
    '5566778899TTJJQQ': [{'sub': 'Q', 'main': 16, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 145}],
    '66778899TTJJQQKK': [{'sub': 'K', 'main': 16, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 146}],
    '778899TTJJQQKKAA': [{'sub': 'A', 'main': 16, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 147}],

    '33445566778899TTJJ': [{'sub': 'J', 'main': 18, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 148}],
    '445566778899TTJJQQ': [{'sub': 'Q', 'main': 18, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 149}],
    '5566778899TTJJQQKK': [{'sub': 'K', 'main': 18, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 150}],
    '66778899TTJJQQKKAA': [{'sub': 'A', 'main': 18, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 151}],

    '33445566778899TTJJQQ': [{'sub': 'Q', 'main': 20, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 152}],
    '445566778899TTJJQQKK': [{'sub': 'K', 'main': 20, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 153}],
    '5566778899TTJJQQKKAA': [{'sub': 'A', 'main': 20, 'name': 'SEQUENCE_TWO', 'type': 7, 'rl': 154}],

    '333444': [{'sub': '4', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 155}],
    '444555': [{'sub': '5', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 156}],
    '555666': [{'sub': '6', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 157}],
    '666777': [{'sub': '7', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 158}],
    '777888': [{'sub': '8', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 159}],
    '888999': [{'sub': '9', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 160}],
    '999TTT': [{'sub': 'T', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 161}],
    'TTTJJJ': [{'sub': 'J', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 162}],
    'JJJQQQ': [{'sub': 'Q', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 163}],
    'QQQKKK': [{'sub': 'K', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 164}],
    'KKKAAA': [{'sub': 'A', 'main': 6, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 165}],

    '333444555': [{'sub': '5', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 166}],
    '444555666': [{'sub': '6', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 167}],
    '555666777': [{'sub': '7', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 168}],
    '666777888': [{'sub': '8', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 169}],
    '777888999': [{'sub': '9', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 170}],
    '888999TTT': [{'sub': 'T', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 171}],
    '999TTTJJJ': [{'sub': 'J', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 172}],
    'TTTJJJQQQ': [{'sub': 'Q', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 173}],
    'JJJQQQKKK': [{'sub': 'K', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 174}],
    'QQQKKKAAA': [{'sub': 'A', 'main': 9, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 175}],

    '333444555666': [{'sub': '6', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 176}],
    '444555666777': [{'sub': '7', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 177}],
    '555666777888': [{'sub': '8', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 178}],
    '666777888999': [{'sub': '9', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 179}],
    '777888999TTT': [{'sub': 'T', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 180}],
    '888999TTTJJJ': [{'sub': 'J', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 181}],
    '999TTTJJJQQQ': [{'sub': 'Q', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 182}],
    'TTTJJJQQQKKK': [{'sub': 'K', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 183}],
    'JJJQQQKKKAAA': [{'sub': 'A', 'main': 12, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 184}],

    '333444555666777': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 185}],
    '444555666777888': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 186}],
    '555666777888999': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 187}],
    '666777888999TTT': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 188}],
    '777888999TTTJJJ': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 189}],
    '888999TTTJJJQQQ': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 190}],
    '999TTTJJJQQQKKK': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 191}],
    'TTTJJJQQQKKKAAA': [{'sub': '7', 'main': 15, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 192}],

    '333444555666777888': [{'sub': '8', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 193}],
    '444555666777888999': [{'sub': '9', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 194}],
    '555666777888999TTT': [{'sub': 'T', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 195}],
    '666777888999TTTJJJ': [{'sub': 'J', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 196}],
    '777888999TTTJJJQQQ': [{'sub': 'Q', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 197}],
    '888999TTTJJJQQQKKK': [{'sub': 'K', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 198}],
    '999TTTJJJQQQKKKAAA': [{'sub': 'A', 'main': 18, 'name': 'SEQUENCE_THREE', 'type': 8, 'rl': 199}],
    # TRIO_SOLO_CHAIN, TRIO_PAIR_CHAIN(rl: 200-267), and FOUR_TWO_SOLO, FOUR_TWO_PAIR(rl: 268-293) are excluded for now

    '3333': [{'name': 'BOMB', 'main': '3', 'type': 9, 'rl': 294}],
    '4444': [{'name': 'BOMB', 'main': '4', 'type': 9, 'rl': 295}],
    '5555': [{'name': 'BOMB', 'main': '5', 'type': 9, 'rl': 296}],
    '6666': [{'name': 'BOMB', 'main': '6', 'type': 9, 'rl': 297}],
    '7777': [{'name': 'BOMB', 'main': '7', 'type': 9, 'rl': 298}],
    '8888': [{'name': 'BOMB', 'main': '8', 'type': 9, 'rl': 299}],
    '9999': [{'name': 'BOMB', 'main': '9', 'type': 9, 'rl': 300}],
    'TTTT': [{'name': 'BOMB', 'main': 'T', 'type': 9, 'rl': 301}],
    'JJJJ': [{'name': 'BOMB', 'main': 'J', 'type': 9, 'rl': 302}],
    'QQQQ': [{'name': 'BOMB', 'main': 'Q', 'type': 9, 'rl': 303}],
    'KKKK': [{'name': 'BOMB', 'main': 'K', 'type': 9, 'rl': 304}],
    'AAAA': [{'name': 'BOMB', 'main': 'A', 'type': 9, 'rl': 305}],
    '2222': [{'name': 'BOMB', 'main': '2', 'type': 9, 'rl': 306}],
    'BR': [{'name': 'ROCKET', 'type': 10, 'rl': 307}],
    'pass': [{'name': 'PASS', 'type': 0, 'rl': 308}],
}
